-- 创建用户表
CREATE TABLE IF NOT EXISTS T_USER (
  USER_ID    INTEGER AUTO_INCREMENT PRIMARY KEY
  COMMENT '用户ID',
  USER_NAME  VARCHAR(30) COMMENT '用户名',
  CREDITS    INTEGER COMMENT '积分',
  PASSWORD   VARCHAR(32) COMMENT '密码',
  LAST_VISIT DATETIME COMMENT '最近访问时间',
  LAST_IP    CHAR(23) COMMENT '最近访问IP'
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT ='用户表';

-- 创建用户登录日志表
CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
  LOGIN_LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY
  COMMENT '登录日志ID',
  UER_ID       INTEGER COMMENT '用户ID',
  IP           CHAR(23) COMMENT 'IP',
  LOGIN_TIME   DATETIME COMMENT '登录时间'
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT = '用户登录日志表';
