-- 创建用户表
CREATE TABLE IF NOT EXISTS T_USER (
  USER_ID    INTEGER AUTO_INCREMENT PRIMARY KEY
  COMMENT '用户ID',
  USER_NAME  VARCHAR(30) COMMENT '用户名',
  PASSWORD   VARCHAR(32) COMMENT '密码',
  CREDITS    INTEGER COMMENT '积分',
  LAST_VISIT DATETIME COMMENT '最近访问时间',
  LAST_IP    CHAR(23) COMMENT '最近访问IP'
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT ='用户表';

-- 创建用户登录日志表
CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
  LOGIN_LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY
  COMMENT '登录日志ID',
  UER_ID       INTEGER COMMENT '用户ID',
  IP           CHAR(23) COMMENT 'IP',
  LOGIN_TIME   DATETIME COMMENT '登录时间'
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT = '用户登录日志表';

-- 论坛版块表
CREATE TABLE IF NOT EXISTS T_BOARD (
  BOARD_ID   INTEGER               AUTO_INCREMENT PRIMARY KEY
  COMMENT '论坛版块ID',
  BOARD_NAME VARCHAR(150) NOT NULL DEFAULT ''
  COMMENT '论坛版块名',
  BOARD_DESC VARCHAR(255)          DEFAULT NULL
  COMMENT '论坛版块描述',
  TOPIC_NUM  INTEGER      NOT NULL DEFAULT '0'
  COMMENT '帖子数目',
  KEY AK_BOARD_NAME (BOARD_NAME)
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1001
  DEFAULT CHARSET = UTF8
  COMMENT = '论坛版块表';

-- 论坛管理表
CREATE TABLE IF NOT EXISTS T_BOARD_MANAGER (
  BOARD_ID INTEGER NOT NULL,
  USER_ID  INTEGER NOT NULL,
  PRIMARY KEY (BOARD_ID, USER_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8
  COMMENT ='论坛管理员';

-- 帖子
CREATE TABLE IF NOT EXISTS T_POST (
  POST_ID  INTEGER  AUTO_INCREMENT PRIMARY KEY
  COMMENT '帖子ID',
  BOARD_ID  INTEGER NOT NULL DEFAULT '0'
  COMMENT '论坛ID',
  TOPIC_ID  INTEGER NOT NULL  DEFAULT '0'
  COMMENT '话题ID',
  USER_ID   INTEGER NOT NULL DEFAULT '0'
  COMMENT '发表者ID',
  POST_TYPE TINYINT(4) NOT NULL DEFAULT '2'
  COMMENT '帖子类型 1:主帖子 2:回复帖子',
  POST_TITLE VARCHAR(50) NOT NULL
  COMMENT '帖子标题',
  POST_TEXT  TEXT        NOT NULL
  COMMENT '帖子内容',
  CREATE_TIME DATE       NOT NULL
  COMMENT '创建时间',
  KEY IDX_TOPIC_ID (TOPIC_ID)
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1001
  DEFAULT CHARSET = UTF8
  COMMENT ='帖子';

-- 话题
CREATE TABLE IF NOT EXISTS T_TOPIC (
  TOPIC_ID      INTEGER               AUTO_INCREMENT PRIMARY KEY
  COMMENT '帖子ID',
  BOARD_ID INTEGER         NOT NULL
  COMMENT '所属论坛',
  TOPIC_TITLE VARCHAR(100) NOT NULL DEFAULT ''
  COMMENT '帖子标题',
  USER_ID     INTEGER      NOT NULL DEFAULT '0'
  COMMENT '发表用户',
  CREATE_TIME DATE         NOT NULL
  COMMENT '发表时间',
  LAST_POST   DATE         NOT NULL
  COMMENT '最后回复时间',
  TOPIC_VIEWS INTEGER      NOT NULL DEFAULT '1'
  COMMENT '浏览数',
  TOPIC_REPLIES INTEGER    NOT NULL   DEFAULT '0'
  COMMENT '回复数',
  DIGEST        INTEGER    NOT NULL
  COMMENT '0:不是精华话题 1:是精华话题',
  KEY IDX_USER_ID (USER_ID),
  KEY IDX_TOPIC_TITLE (TOPIC_TITLE)
)
  ENGINE = INNODB
  AUTO_INCREMENT = 24
  DEFAULT CHARSET = UTF8
  COMMENT ='话题';