-- 创建用户表
CREATE TABLE IF NOT EXISTS T_USER (
  USER_ID     INTEGER AUTO_INCREMENT PRIMARY KEY,
  USER_NAME   VARCHAR(30),
  CREDITS     INTEGER,
  PASSWORD    VARCHAR(32),
  LAST_VISIT  DATETIME,
  LAST_IP     CHAR(23),
  UPDATE_TIME DATETIME
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT ='用户表';

-- 创建用户登录日志表
CREATE TABLE IF NOT EXISTS T_LOGIN_LOG (
  LOGIN_LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
  UER_ID       INTEGER,
  IP           CHAR(23),
  LOGIN_TIME   DATETIME
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT = '用户登录日志表';
