package com.dranawhite.mybatis.model;

public class PersonPO {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.T_PERSON.ID
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.T_PERSON.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.T_PERSON.AGE
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.T_PERSON.PHONE
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCOTT.T_PERSON.ADDRESS
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.T_PERSON.ID
     *
     * @return the value of SCOTT.T_PERSON.ID
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.T_PERSON.ID
     *
     * @param id the value for SCOTT.T_PERSON.ID
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.T_PERSON.NAME
     *
     * @return the value of SCOTT.T_PERSON.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.T_PERSON.NAME
     *
     * @param name the value for SCOTT.T_PERSON.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.T_PERSON.AGE
     *
     * @return the value of SCOTT.T_PERSON.AGE
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.T_PERSON.AGE
     *
     * @param age the value for SCOTT.T_PERSON.AGE
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.T_PERSON.PHONE
     *
     * @return the value of SCOTT.T_PERSON.PHONE
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.T_PERSON.PHONE
     *
     * @param phone the value for SCOTT.T_PERSON.PHONE
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCOTT.T_PERSON.ADDRESS
     *
     * @return the value of SCOTT.T_PERSON.ADDRESS
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCOTT.T_PERSON.ADDRESS
     *
     * @param address the value for SCOTT.T_PERSON.ADDRESS
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}