-- 创建用户表
CREATE TABLE IF NOT EXISTS T_USER (
  USER_ID    INTEGER AUTO_INCREMENT PRIMARY KEY
  COMMENT '用户ID',
  USER_NAME  VARCHAR(30) COMMENT '用户名',
  PASSWORD   VARCHAR(32) COMMENT '密码',
  CREDITS    INTEGER COMMENT '积分',
  LAST_VISIT DATETIME COMMENT '最近访问时间',
  LAST_IP    CHAR(23) COMMENT '最近访问IP'
)
  ENGINE = INNODB
  AUTO_INCREMENT = 1001
  DEFAULT CHAR SET = UTF8
  COMMENT ='用户表';